// Data
let translations = [
    "Hırsızı gördün mü? -> Did you see the thief?",
    "Susadın mı? -> Are you thirsty?",
    "Odanı topladın mı? -> Did you tidy your room?",
    "Pantolonum nerede? -> Where are my pants/trousers?",
    "Makasım nerede? -> Where are my scissors?",
    "Havlum nerede? -> Where is my towel?",
    "Bugün kalın montumu giyeceğim. -> I will wear my thick coat today.",
    "Biz daha başarılıyız. -> We are more succesfull.",
    "Bugün hiç para harcamadım. -> I didn't spend any money today.",
    "Rafı temizledin mi? -> Did you clean the shelf?",
    "Çekmeceyi temizledin mi? -> Did you clean the drawer?",
    "Fiyat her gün yükseliyor. -> The price is rising every day.",
    "Acıktım. -> I got hungry.",
    "Evlendik. -> We got married.",
    "Fiyat yükseldi. -> The price got high.",
    "Fiyat yükseliyor. -> The price is getting high every day.",
    "Yoruldum. -> I got tired.",
    "Bir günlüğüne ödünç verebilir misin? -> Can you lend for a day?",
    "Bir günlüğüne ödünç alabilir miyim? -> Can I borrow for a day?",
    "Lavabo nerede? -> Where is the restroom?",
    "Bugün pilav pişireceğim. -> I will cook rice today.",
    "Buzdolabında. -> It is in the refrigerator/fridge.",
    "Nasıl ödeyeceksiniz? Kartla mı, Nakit mi? -> How will you pay? By card or cash",
    "Çamaşır makinesinde. -> It is in the washing machine.",
    "Bulaşık makinesinde. -> It is in the dishwasher.",
    "Fırında. -> It is in the oven.",
    "Hatayı düzelttin mi? -> Did you correct the fault/mistake?",
    "Senin ana dilin ney? -> What is your main language?",
    "Neden gülüyorsun? -> Why are you laughing?",
    "Neden öksürüyorsun? -> Why are you caughing?",
    "Sağlığın nasıl? -> How is your health?",
    "Bu alışkanlığı sevmiyorum. -> I don't like this habbit.",
    "Uzak mı? -> Is it far?",
    "Ne kadar uzak? -> How far is it?",
    "Biz nişanlıyız. -> We are engaged.",
    "Biz boşandık. -> We are divorced.",
    "Çizebilir misin? -> Can you draw it?",
    "Korkmadım. -> I was not afraid.",
    "Onlar nişanlı. -> They are engaged.",
    "Onlar evli mi? -> Are they married?",
    "Onlar boşanmış. -> They are divorced.",
    "Dün yolda düştüm. -> I did fall on the way yesterday.",
    "Üzüm kaç para? -> How much money is grape?",
    "Bu alışkanlığı sevmiyorum. -> I don't like this habbit.",
    "Bir günlüğüne ödünç verebilir misin? -> Can you lend for a day?",
    "Kıştan nefret ediyorum. -> I hate winter.",
    "Temizlik yapmaktan nefret ediyorum. -> I hate cleaning.",
    "Yemek yapmaktan nefret ederim. -> I hate cooking.",
    "Yemek yapmayı severim. -> I like cooking.",
    "Yemek yapmaya bayılırım. -> I love cooking.",
    "Yemek yapmaktan keyif alırım. -> I enjoy cooking.",
    "(Yemek)Afiyet olsun. -> Enjoy your meal.",
    "(İçecek)Afiyet olsun. -> Enjoy your drink.",
    "Sağlığım iyi. -> My health is well.",
    "Beni duyabiliyor musun? -> Can you hear me?",
    "Çok ağır değil. -> It is not very heavy.",
    "Çok yüksek değil. -> It is not very high.",
    "Tarih dersini severim. -> I like history lesson.",
    "Ben korku filmi seyretmem. -> I don't watch horror movie.",
    "Geçen hafta hastaydım. -> I was very ill last week.",
    "Siz gazetecemisiniz? -> Are you journalist?",
    "Ben büyük beden giyiyorum. -> I wear large size.",
    "Neden gülüyorsun? -> Why are you laughing?",
    "Neye gülüyorsun? -> What are you laughing at?",
    "Ben hukuk okuyorum. -> I study law.",
    "Bu sabah evden 9'da çıktım. -> I left home at nine o'clock this morning.",
    "Otobüs saat 3'de kalkacak. -> The bus will leave at three o'clock.",
    "Otobüs saat 3'de kalkıyor. -> The bus is leaving at three o'clock.",
    "Dün kütüphadeydim. -> I was in the library yesterday.",
    "Öğlen yemeğini nerede yiyelim? -> Where shall we have lunch?",
    "Bizim müdür nerede? -> Where is our manager?",
    "Bu benim asıl işim değil. -> This is not my main job.",
    "Benim harita çalışmıyor. -> My map is not working.",
    "Düzelttin mi? -> Did you correct?",
    "Çok zor değil. -> It is not very difficult.",
    "Bugün hava kış gibi. -> The weather is like winter today.",
    "Harikaydı(Muheteşemdi). -> It was wonderful.",
    "Ben bu kelimeyi bilmiyorum. -> I don't know this word.",
    "Ayakkabılarımı giyiyorum. -> I am wearing my shoes.",
    "İnternet burada daha zayıf. -> The internet is weaker here.",
    "İnternet burada daha iyi. -> The internet is better here.",
    "İnternet burada daha kötü. -> The internet is worse here.",
    "Bu karpuz kaç kilo? -> How many kilos is this watermelon?",
    "Duvarda. -> It is on the wall.",
    "Garson mutfakta. -> The waiter is in the kitchen.",
    "Garson(Kadın) mutfakta. -> The waitress is in the kitchen.",
    "Sizi anlamıyorum. -> I don't understand you.",
    "Sizi anlayamıyorum. -> I can't understand you.",
    "Şemsiyem kırık. O yüzden kullanamıyorum. -> My umbrella is broken. So/That's why I can't use",
    "Sen çirkin değilsin. -> You are not ugly.",
    "Sen şişman değilsin. -> You are not fat.",
    "Biraz kilolusun. -> You are a little overweight.",
    "Pantolonum nerede? -> Where are my pants/trousers(ingiliz)?",
    "Ayakkabılarım nerede? -> Where are my shoes?",
    "Ayakkabım nerede? -> Where is my shoe?",
    "Çoraplarım nerede? -> Where are my socks?",
    "Gözlüğüm nerede? -> Where are my glasses?",
    "Güneş gözlüğüm nerede? -> Where are my sunglasses?",
    "Makasım nerede? -> Where are my scissors?",
    "Bu zeytin ağacı mı? -> Is this olive tree?",
    "Yarın seyahat acentesine gideceğim. -> I will go to travel agency.",
    "Bu iyi bir alışkanlık değil. -> This is not a good habbit.",
    "Kahve sever misin? -> Do you like coffee?",
    "Kahveden nefret ederim. -> I don't hate coffee.",
    "Senden nefret etmiyorum. -> I don't hate you.",
    "Sağlığım iyi. -> My health is fine.",
    "Zili duymadım. -> I didn't hear the bell.",
    "Çok ağırdı. -> It was very heavy.",
    "Çok yüksekti. -> It was very high.",
    "Tarih dersi ne zaman? -> When is the history lesson?",
    "Tarih sınavı ne zaman? -> When is the history exam?",
    "Korku filmi seyredelim mi? -> Shall we watch a horror movie?",
    "Çok açım. -> I am so hungry.",
    "Çok hastayım. -> I am so ill.",
    "Siz gazeteci misiniz? -> Are you a journalist?",
    "Bizim ev yeterince geniş. -> Our house is large enough.",
    "Yeterince param var. -> I have enough money.",
    "Neden gülüyorsunuz? -> Why are you laughing?",
    "Neden öksürüyorsun? -> Why are you coughing?",
    "Mezun olunca avukat olacağım. -> I will be a lawyer when I graduate.",
    "Evden saat kaçta çıktın? -> What time did you leave home?",
    "Bu sabah evden 8'de çıktım. -> I did leave from home at eight o'clock this morning.",
    "Sanırım solda. -> I think it is on the left.",
    "Sana kaç para borç verdi? -> How much money did he lend you?",
    "Bizim şirkette 10 tane muhasebeci çalışıyor. -> Ten accountants work in our company.",
    "Uçaktan korkar mısın? -> Are you afraid of airplane?",
    "Ben onun(kadın) yaşını bilmiyorum. -> I don't know her age.",
    "Dün çok sinirliydim. -> I was so angry yesterday.",
    "Bizim şirkette 15 tane mimar var. -> There are fifteen architects in our company.",
    "Oraya varınca beni arar mısın? -> Do you call me when you arrive there?",
    "Senin kaç tane teyzen var? -> How many aunts do you have?",
    "Faturayı ne zaman ödeyeceksin? -> When will you pay the bill?",
    "Patates haşladım. -> I boiled potato.",
    "Ben senin gibi cesur değilim -> I am not brave like you.",
    "Benim gibi cesur olmalısın. -> You should be brave like me.",
    "Patron İzmir'e gitti. -> The boss went to İzmir.",
    "Bu kitabı kitapçıdan aldım. -> I bought this book from bookstore.",
    "Ne kadar borç aldın? -> How much did you borrow?",
    "Dikkatli ol. Kırma -> Be careful. Don't break.",
    "Yerleri fırçaladın mı? -> Did you brush the floor?",
    "Tereyağı için ne kadar para ödedin? -> How much money did you pay for butter?",
    "Buraya yeni bir otel inşa edecekler. -> They will build a new hotel here.",
    "Hesap makinem bozuk. -> My calculator is broken.",
    "Hesap makinem çalışmıyor. -> My calculator is not working.",
    "Ofiste takvim var mı? -> Is there calender in the office?",
    "Başkentte ne kadar kalacaksın? -> How long will you stay in the capital?",
    "Öğleden sonra marangoz gelecek. -> The carpenter will come in the afternoon.",
    "Halıları temizliyorum. -> I am cleaning the carpets.",
    "Taşıyamıyorum. Yardım edebilir misin? -> I can't carry. Can you help me?",
    "Çocuklar nerede? -> Where are the children?",
    "Çizgi film seyrediyorlar. -> They are watching cartoon.",
    "Sandalye alabilir miyim? -> Can I have the chair?",
    "Bu daha ucuz. -> This is cheaper.",
    "Bugün hava açık. -> The weather is clear today.",
    "Geçen ay ne kadar para kazandın? -> How much money did you earn last week?",
    "Haberleri izledin mi? -> Did you watch news?",
    "Ben hiç haber izlemem. -> I never watch news.",
    "Fırının karşısında. -> It is opposite the bakery.",
    "Bakkalın yanında. -> It is next to the grocery.",
    "Kasabın arkasında. -> It is behind the butcher.",
    "Kasap ve manavın arasında. -> It is between the butcher and the greengrocery.",
    "Terzinin önünde. -> It is in front of the tailor.",
    "Yarın veli toplantısı var. -> There is a parent meeting tomorrow.",
    "Hala sandalyeyi boyuyorum. -> I am still painting the chair.",
    "Ne zaman ödeyeceksin. -> When will you pay?",
    "Bugün hiç para harcadın mı? -> Did you spend any money today?",
    "Bugün hava daha soğuk. -> The weather is colder today.",
    "Bugün hava daha serin. -> The weather is cooler today.",
    "Hangisi daha ucuz? -> Which one is cheaper?",
    "Hangisi daha iyi? -> Which one is better?",
    "Hangisi daha lezzetli? -> Which one is more delicious?",
    "Hangisi daha kaliteli? -> Which one is of higher quality?",
    "Bu daha ağır. -> This is heavier.",
    "Bu daha kolay. -> This is easier.",
    "Bu daha komik. -> This is funnier.",
    "Eğer isterseniz yarın daha erken gelebilirim. -> I can come earlier tomorrow if you want.",
    "Bu kişisel bir toplantı. -> This is a personal meeting.",
    "Mümkün değil. -> It is not possible.",
    "Demir yolunu tamir ettiler. -> They repaired the railway.",
    "Sessiz olabilir misin? Lütfen. -> Can you be quiet? Please.",
    "Havuzda yüzelim mi? -> Shall we swim in the pool?",
    "Biber ne kadar? -> How much is the pepper?",
    "Sınavdan geçemedim. -> I couldn't pass the exam.",
    "Sınavdan kaldım. -> I failed the exam.",
    "Hatırlayamadım. -> I couldn't remember.",
    "Tekrar edebilir misin? Lütfen. -> Can you repeat? Please.",
    "Tekrar söyleyebilir misin? -> Can you say again? Please.",
    "Buzdolabında. -> It is in the refrigerator.",
    "Dönüş biletini satın aldım. -> I bought the return ticket.",
    "Biz daha zenginiz. -> We are richer.",
    "Biz daha fakiriz. -> We are poorer.",
    "Biz daha güçlüyüz. -> We are stronger.",
    "Biz daha zekiyiz. -> We are smarter.",
    "Biz daha güçlüyüz. -> We are stronger.",
    "Biz daha başarılıyız. -> We are more successful.",
    "İlginç bir hikaye. -> It is an interesting story.",
    "Tadı nasıl? -> How does it taste?",
    "Tadı tatlı. -> It tastes sweet.",
    "Tadı ekşi. -> It tastes sour.",
    "Orada 3 gün kalacağım. -> I will stay there three days.",
    "Orada 3 gün kaldım. -> I did stay there three days.",
    "Kaşığımı düşürdüm. -> I dropped my spoon.",
    "Yeni bir tane alabilir miyim? -> Can I have a new one?",
    "Bıçağımı düşürdüm. -> I dropped my knife.",
    "Yeni bir tane alabilir miyim? Lütfen -> Can I have a new one? Please.",
    "Çok param var. -> I have much money.",
    "Çok pahalı. -> It is very expensive.",
    "Bugün çok para harcadım. -> I spent a lot of money today.",
    "Ne çorbanız var? -> What soup do you have?",
    "Bu şarkıya bayılıyorum. -> I love this song.",
    "Kaç tane oğlun var. -> How many sons do you have?",
    "Kaç tane kızın var. -> How many daughters do you have?",
    "Çoraplarım nerede? -> Where are my socks?",
    "Eteği kaça aldın? -> How much did you pay for the skirt?",
    "Tek kişilik oda ne kadar? -> How much is a single room?",
    "Çift kişilik oda ne kadar? -> How much is a double room?",
    "Ben şarkı söyleyemem. Çünkü sesim çok kötü. -> I can't sing because my voice is very bad.",
    "Kar yağıyor. Kalın montunu giy. -> It is snowing. Wear your thick coat.",
    "Gülümseyebilir misin? Please -> Can you smile? Please.",
    "Yanılıyorsun/Yanlışsın. -> You are wrong?",
    "Yanılıyor muyum? -> Am I wrong?",
    "Haklısın. -> You are right.",
    "Bu kelimeyi bilmiyorum. -> I don't know this word.",
    "İlkbaharda İzmir'e gideceğim. -> I will go to İzmir in spring.",
    "Ayakkabını giydin mi? -> Did you wear your shoes?",
    "Ben gözlük takmam. -> I don't wear sunglasses.",
    "İnternet bugün zayıf: -> The internet is weak today.",
    "Karpuz kaç para? -> How much is watermelon?",
    "Amcam nerede? -> Where is my uncle?",
    "Yağmur yağıyor. Yanına şemsiyeni al. -> It is raining. Take your umbrella with you.",
    "Çok çirkin. -> It is so ugly.",
    "Küçük bir kasaba yaşıyor. -> He lives in a small town.",
    "Banyoda hiç temiz havlu yok. -> There isn't any clean towel in the bathroom.",
    "Diş fırçam nerede? -> Where is my toothbrush?",
    "Aynanın önünde. -> It is in front of the mirror.",
    "Diş macunu nerede? -> Where is toothpaste?",
    "O da aynanın önünde. -> It is in front of the mirror too.",
    "Odadı topladın mı? -> Did you tidy your room?",
    "Kaç tane biletin var? -> How many tickets do you have?",
    "Susadın mı? -> Are you thirsty?",
    "Hırsızı gördün mü? -> Did you see the thief?",
    "Ben daha zayıfım. -> I am thinner.",
    "Ben daha şişmanım. -> I am fatter.",
    "Daha güçlüyüm. -> I am stronger.",
    "Ben daha yakışıklıyım. -> I am more handsome.",
    "Benim kalın montum nerede? -> Where is my thick coat?",
    "Ben senden daha uzun boyluyum. -> I am taller than you.",
    "Ben senden daha zenginim. -> I am richer than you.",
    "Ben senden daha fakirim. -> I am poorer than you.",
    "Ben senden daha başarılıyım. -> I am more successful than you.",
    "Tatlı mı? -> Is it sweet?",
    "Ekşi mi? -> Is it sour?",
    "Sen ne öğretiyorsun? -> What do you teach?",
    "Yine takım elbise mi giyeceksin? -> Will you wear a suit again?",
    "Kız kardeşim muhasebeci. -> My sister is an accountant.",
    "Dişçiden korkar mısın? -> Are you afraid of the dentist?",
    "Dişçiden korkmam. -> I am not afraid of the dentist.",
    "Onun yaşını bilmiyorum. -> I don't know his age.",
    "Erkek kardeşim bir mimar. -> My brother is an architect.",
    "Ne zaman vardınız? -> When did you arrive?",
    "Teyzem nerede? -> Where is my aunt?",
    "İzmire gitti. -> She went to İzmir.",
    "O neden gitti? -> Why did she go?",
    "Kızını görmek için gitti. -> She went to see her daughter.",
    "Ne zaman gitti? -> When did she go?",
    "İki gün önce gitti. -> She went two days ago.",
    "Nasıl gitti? -> How did she go?",
    "Otobüsle gitti. -> She went by bus.",
    "Orada ne kadar süre kalacak? -> How long will she stay there?",
    "Orada kaç gün kalacak? -> How many days will she stay there?",
    "Ne zaman geri dönecek? -> When will she come back? / When will she return?",
    "İki gün sonra geri dönecek. -> She will return two days later.",
    "Çantan yeni mi? -> Is your bag new?",
    "Faturayı ödedin mi? -> Did you pay the bill?",
    "Doğalgaz faturasını ödedin mi? -> Did you pay the natural gas bill?",
    "Ne kaynatıyorsun? -> What are you boiling?",
    "Patates kaynatıyorum. -> I am boiling potatoes.",
    "Patates kızartıyorum. -> I am frying potatoes.",
    "Patates pişiriyorum. -> I am cooking potatoes.",
    "Patates fırınlıyorum. -> I am baking potatoes.",
    "Buralarda kitapçı var mı? -> Is there a bookstore here?",
    "Uzak mı? -> Is it far?",
    "Ne kadar uzak? -> How far is it?",
    "Buradan 400 metre uzakta. -> It is four hundred meters away from here.",
    "Kalemini ödünç alabilir miyim? -> Can I borrow your pencil?",
    "Bizim patron İzmir'e gitti. -> Our boss went to İzmir.",
    "Köprünün yakınında. -> It is near the bridge.",
    "Ben kırmadım. -> I didn't break.",
    "O kırdı. -> She broke.",
    "Fırçamı arıyorum. -> I am looking for my brush.",
    "Takvimi kontrol ettin mi? -> Did you check the calendar?",
    "Ben günde iki kere takvimi kontrol ederim. -> I check the calendar twice a day.",
    "İzliyorum. -> I am watching.",
    "İzledim. -> I watched.",
    "İzleyelim mi? -> Shall we watch?",
    "İzlicem. -> I will watch.",
    "İzleyebilirim. -> I can watch.",
    "İzlerim. -> I watch.",
    "İzlemeliyim. -> I should watch.",
    "Köprü nerede? -> Where is the bridge? | bridge: köprü",
    "Köprü sağ tarafta. -> It is on the right side.",
    "Çok cesursun. -> You are so brave.",
    "Dişçiden korkuyor musun? -> Are you afraid of the dentist?",
    "Ben dişçiden korkmam. -> I am not afraid of the dentist.",
    "Kız kardeşim bir muhasebeci. -> My sister is an accountant.",
    "Onun(Erkek) yaşını bilmiyorum. -> I don't know his age.",
    "Onun yaşını biliyor musun? -> Do you know his age?",
    "Yalnız mı gideceksin? -> Will you go alone?",
    "Uçakla mı gideceksin? -> Will you go by plane?",
    "Ben bugün sinirli değilim. -> I am not angry today.",
    "İzmire vardınız mı? -> Did you arrive in İzmir?",
    "Teyzem İzmire gitti. -> My aunt went to İzmir.",
    "O(Kadın) banyoda. -> She is in the bathroom. | bathroom: banyo",
    "Faturayı ödedin mi? -> Did you pay the bill? | bill: fatura",
    "Hayır, Yarın ödeyeceğim. -> No, I will pay tomorrow.",
    "Yumurta mı haşlıyorsun? -> Are you boiling eggs? | boil: haşlamak, kaynamak",
    "Kitapçıya gidelim mi? -> Shall we go to the bookstore? -> bookstore: Kitap mağazası",
    "Beğenmedim. -> I didn't like.",
    "Çünkü çok sıkıcı. -> Because it is boring.",
    "Kalemini ödünç alabilir miyim? -> Can I borrow your pencil? | borrow: ödünç almak, borç almak",
    "Kalemini 5 dakikalığına ödünç alabilir miyim? -> Can I borrow your pencil for five minutes?",
    "Patron nerede? -> Where is the boss? | boss: patron",
    "Kaç kutu istiyorsun? -> How many boxes do you want?",
    "Fırçam nerede? -> Where is my brush? | brush: fırça",
    "Fırçamı arıyorum. -> I am looking for my brush.",
    "Ne arıyorsun? -> What are you looking for?",
    "Bişey mi arıyorsun? -> Are you looking for something?",
    "Dinliyorum. -> I am listening.",
    "Dinlerim. -> I listen.",
    "Dinleyebilirim. -> I can listen.",
    "Dinleyelim mi? -> Shall we listen?",
    "Dinleyeceğim. -> I will listen.",
    "Dinledim. -> I did listen.",
    "Dinlemelisin. -> You should listen.",
    "Demir yolunu tamir ediyorlar. -> They are repairing the railway.",
    "İtebilir misin? -> Can you push?",
    "İtmelisin? -> You should push.",
    "Kapıyı açmak için itmelisin. -> You should push the door to open.",
    "Ekmek almak için bakkala gittim. -> I went to the supermarket to buy bread.",
    "Ekmek almak için bakkala gittim. -> I went to the supermarket for buying bread.",
    "Kapıyı açmak için çekmelisin. -> You should pull the door to open.",
    "Hazır mısın? -> Are you ready?",
    "On dakika sonra hazır olacağım. -> I will be ready after ten minutes.",
    "Geri dönecek misin? -> Will you return?",
    "Ne zaman geri döneceksin? -> When will you return?",
    "Salı günü geri döneceğim. -> I will return on Tuesday.",
    "Dönüş biletini aldın mı? -> Did you buy the return ticket?",
    "Üç defa tekrar ettim. -> I repeated three times.",
    "Sessiz bir yer. -> It is a silent place. / It is a quiet place.",
    "Buzdolabı bozuk. -> The refrigerator is broken. / The fridge is broken.",
    "Kira için ne kadar ödüyorsunuz? -> How much do you pay for the rent?",
    "Lavabo nerede? -> Where is the restroom?",
    "Pilav pişirelim mi? -> Shall we cook rice?",
    "Öğlen yemeğini yedin mi? -> Did you eat lunch? / Did you have lunch?",
    "Kahvaltı yaptın mı? -> Did you have breakfast?",
    "Yarın buluşalım mı? -> Shall we meet tomorrow?",
    "Bugün ne yemeği pişirdin? -> What meal did you cook today?",
    "İngilizce konuşur musun? -> Do you speak English?",
    "Araba sürmesini biliyor musun? -> Do you know how to drive?",
    "Tamir etmesini biliyor musun? -> Do you know how to repair?",
    "Beni özledin mi? -> Did you miss me?",
    "Onu özledin mi? -> Did you miss him?",
    "Onları özledin mi? -> Did you miss them?",
    "Ben bu komşuyu tanımıyorum. -> I don't know this neighbor.",
    "Ben bu komşuları tanımıyorum. -> I don't know these neighbors.",
    "Geçen yıl öğrenciydim. -> I was a student last year.",
    "Dün çok meşguldüm. -> I was very busy yesterday.",
    "Seni arayamadım. -> I couldn't call you.",
    "Kusura bakma. Seni arayamadım. Dün çok yoğundum. -> I'm sorry. I couldn't call you. Because I was too busy yesterday.",
    "Bu daha ucuz. -> This is cheaper.",
    "Bu daha pahalı. -> This is more expensive.",
    "Bu sınav daha zor. -> This exam is harder.",
    "Şu gömleği beğendim. -> I like that shirt.",
    "Hangisi? -> Which one?",
    "Beyaz olan. -> The white one.",
    "Ben mavi olanı beğendim. -> I like the blue one.",
    "Bence mavi olan daha iyi. -> I think the blue one is better.",
    "Ben koyu renk severim. -> I like dark color.",
    "Ben açık renk severim. -> I like light color.",
    "Benim silahım yok. -> I don't have a gun.",
    "Benim kötü alışkanlığım yok. -> I don't have a bad habit.",
    "Bir çatal alabilir miyim? -> Can I have a fork, please?",
    "Bir kaşık alabilir miyim? -> Can I have a spoon, please?",
    "Bir bıçak alabilir miyim? -> Can I have a knife, please?",
    "Bir tabak alabilir miyim? -> Can I have a plate, please?",
    "Tereyağ nerede? -> Where is the butter?",
    "Tereyağ buzdolabında. -> It is in the fridge/refrigerator.",
    "Bardağım nerede? -> Where is my glass?",
    "Bulaşık makinesinde. -> It is in the dishwasher.",
    "Gömleğim nerede? -> Where is my shirt?",
    "Çamaşır makinesinde. -> It is in the washing machine.",
    "Kurabiyeler nerede? -> Where are the cookies?",
    "Fırında. -> They are in the oven.",
    "Yemek nerede? -> Where is the meal?",
    "Ocağın üstünde. -> It is on the stove/burner.",
    "Patates haşlıyorum. -> I am boiling potatoes.",
    "Patates pişiriyorum. -> I am cooking potatoes.",
    "Patates kızartıyorum. -> I am frying potatoes.",
    "Patatesi fırının içinde pişiriyorum. -> I am baking potatoes.",
    "Ben haşlanmış patates istiyorum. -> I want boiled potatoes.",
    "Ben kızarmış patates istiyorum. -> I want fried potatoes.",
    "Ben fırınlanmış patates istiyorum. -> I want baked potatoes.",
    "Uzak mı? -> Is it far?",
    "Ne kadar uzak? -> How far is it?",
    "Senin uçuş ne zaman? -> When is your flight?",
    "Senin doğum günün ne zaman? -> When is your birthday?",
    "Şişman mı? -> Is she fat?",
    "Zayıf mı? -> Is he thin?",
    "Üzüm ne kadar? -> How much is grape?",
    "Bir fincan çay istiyorum. -> I want a cup of tea.",
    "Bir bardak su istiyorum. -> I want a glass of water.",
    "Bir şişe süt istiyorum. -> I want a bottle of milk.",
    "Bir kutu çikolata istiyorum. -> I want a box of chocolate.",
    "Dişlerini fırçaladın mı? -> Did you brush your teeth?",
    "Çay ister misin? -> Do you want tea?",
    "Ben bir fincan çay istiyorum. -> I want a cup of tea.",
    "Bir bardak su istiyorum. -> I want a glass of water.",
    "Bir şişe süt istiyorum. -> I want a bottle of milk.",
    "Bir kutu çikolata istiyorum. -> I want a box of chocolate.",
    "Bir kavanoz reçel istiyorum. -> I want a jar of jam.",
    "Ben mühendisim. -> I am an engineer.",
    "Babam avukat. -> My father is a lawyer.",
    "Annem muhasebeci. -> My mother is an accountant.",
    "Erkek kardeşim marangoz. -> My brother is a carpenter.",
    "Kız kardeşim bir mimar. -> My sister is an architect.",
    "Karanlıktan korkar mısın? -> Are you afraid of darkness?",
    "Benden korkuyor musun? -> Are you afraid of me?",
    "Ben senden korkmuyorum. -> I am not afraid of you. / I am not scared of you.",
    "Biz aynı yaşta değiliz. -> We aren't the same age.",
    "Kızgın mısın? -> Are you angry?",
    "Neden kızgınsın? -> Why are you angry?",
    "Cevabın var mı? -> Do you have an answer?",
    "Soruma cevap verebilir misin? -> Can you answer my question?",
    "Bir soru sorabilir miyim? -> Can I ask a question?",
    "Uçakla gidelim mi? -> Shall we go by airplane?",
    "Bu sefer uçakla gidelim mi? -> Shall we go by airplane this time?",
    "Geçen sefer trenle gittik. -> We went by train last time.",
    "Bir daha ki sefere gemi ile gidelim mi? -> Shall we go by ship next time?",
    "Saat üç'te varırız. -> We arrive at three o'clock.",
    "Oraya saat üç'te varırız. -> We arrive there at three o'clock.",
    "Ödedin mi? -> Did you pay?",
    "Kaç para ödedin? -> How much did you pay?",
    "Okudun mu? -> Did you read?",
    "Kaç sayfa okudun? -> How many pages did you read?",
    "Yazdın mı? -> Did you write?",
    "Kaç sayfa yazdın? -> How many pages did you write?",
    "Boyadın mı? -> Did you paint?",
    "Nereyi boyadın? -> Where did you paint?",
    "Bu benim kişisel bilgisayarım. -> This is my personal computer.",
    "Kaç kişi var? -> How many people are there?",
    "Toplantıda kaç kişi var? -> How many people are there in the meeting?",
    "Sınıfta kaç öğrenci var? -> How many students are there in the classroom?",
    "Kaç kişisiniz? -> How many people are you?",
    "Onlar kaç kişi? -> How many people are they?",
    "Bir şey içmek ister misiniz? -> Do you want to drink something?",
    "Ne içmek istersiniz? -> What do you want to drink?",
    "Bir şeyler yemek ister misiniz? -> Do you want to eat something?",
    "Ne yemek istersiniz? -> What do you want to eat?",
    "Ben çay istiyorum. -> I want to drink tea.",
    "Ben çay içeceğim. -> I will drink tea.",
    "Bir fincan kahve alabilir miyim? -> Can I have a cup of coffee?",
    "Bir bardak su alabilir miyim? -> Can I have a glass of water?",
    "Bir şişe süt alabilir miyim? -> Can I have a bottle of milk? Please",
    "Bir kutu çikolata alabilir miyim? -> Can I have a box of chocolate? Please",
    "Bir kavanoz reçel alabilir miyim? -> Can I have a jar of jam? Please",
    "Yarın veli toplantısı var. -> There is a parent meeting tomorrow.",
    "Gömlek kaç para? -> How much is the shirt?",
    "Bu gömlek ne kadar? -> How much is this shirt?",
    "Ciddi misin? -> Are you serious?",
    "Arabamı satacağım. -> I will sell my car.",
    "Onlar aynı değil. -> They aren't the same.",
    "Onlar farklı. -> They are different.",
    "Bisiklet sürebilir misin? -> Can you ride a bicycle?",
    "Paran var mı? -> Do you have money?",
    "Kitap okur musun? -> Do you read a book?",
    "Bilgisayar oyunu oynar mısın? -> Do you play computer games?",
    "Televizyon izler misin? -> Do you watch TV?",
    "Kaç(Ne kadar) paran var? -> How much money do you have?",
    "10 bin liram var. -> I have ten thousand liras.",
    "Param yok. -> I don't have money.",
    "Hiç param yok. -> I don't have any money.",
    "Yarın toplantın var mı? -> Do you have a meeting tomorrow?",
    "Yarın kaç tane toplantın var? -> How many meetings do you have tomorrow?",
    "Yarın toplantı var mı? -> Is there a meeting tomorrow?",
    "Yarın iki tane toplantı var. -> There are two meetings tomorrow.",
    "Çay içelim mi? -> Shall we drink tea?",
    "Sinemaya gidelim mi? -> Shall we go to the cinema?",
    "Saat kaç? -> What time is it?",
    "Saat 8. -> It is eight o'clock.",
    "Toplantı saat kaçta? -> What time is the meeting?",
    "Toplantı saat 3'te. -> It is at three o'clock.",
    "Toplantı ne zaman? -> When is the meeting?",
    "Toplantı çarşamba gününde. -> It is on Wednesday.",
    "Toplantı Nisanda. -> It is in April.",
    "Seyahat eder misin? -> Do you travel?",
    "Kitap okur musun? -> Do you read books?",
    "Ne kadar sık seyahat edersin? -> How often do you travel?",
    "Ben her zaman seyahat ederim. -> I always travel.",
    "Ben sık sık seyahat ederim. -> I often travel.",
    "Genellikle seyahat ederim. -> I usually travel.",
    "Bazen seyahat ederim. -> I sometimes travel.",
    "Nadiren seyahat ederim. -> I rarely travel.",
    "Ben hiç seyahat etmem. -> I never travel.",
    "Günde bir sefer seyahat ederim. -> I travel once a day.",
    "Haftada iki kere seyahat ederim. -> I travel twice a week.",
    "Ayda üç sefer seyahat ederim. -> I travel three times a month.",
    "İki ayda bir seyahat ederim. -> I travel every two months.",
    "Kadıköy'e her 10 dakikada bir otobüs var. -> There is a bus to Kadıköy every ten minutes.",
    "10 dakikada bir antibiyotik alıyorum. -> I take antibiotics every eight hours.",
    "Başın ağrıyor mu? -> Do you have a headache?",
    "Sırtın ağrıyor mu? -> Do you have backache?",
    "Miden ağrıyor mu? -> Do you have stomachache?",
    "Dişin ağrıyor mu? -> Do you have a toothache?",
    "Ateşin var mı? -> Do you have a fever?",
    "Doktora gitmelisin -> You should go to the doctor.",
    "Dinlenmelisin -> You should rest.",
    "Aç mısın? -> Are you hungry?",
    "Bir şeyler yiyelim mi? -> Shall we eat something?",
    "Susadın mı? -> Are you thirsty?",
    "Bir şeyler içelim mi? -> Shall we drink something?",
    "Yarın buluşalım mı? -> Shall we meet tomorrow?",
    "Yarın beni arayabilir misin? -> Can you call me tomorrow?",
    "Yarın bizi arayabilir misin? -> Can you call us tomorrow?",
    "Yarın onu(erkek) arayabilir misin? -> Can you call him tomorrow?",
    "Yarın onu(bayan) arayabilir misin? -> Can you call her tomorrow?",
    "Yarın onları arayabilir misin? -> Can you call them tomorrow?",
    "Kitap okur musun? -> Do you read a book?",
    "Öğrenci misin? -> Are you a student?",
    "Paran var mı? -> Do you have money?",
    "Kaç paran var? -> How much money do you have?",
    "Yarın dersin var mı? -> Do you have a lesson tomorrow?",
    "Kaç tane dersin var? -> How many lessons do you have?",
    "Yarın ders var mı? -> Is there a lesson tomorrow?",
    "Bankanın önünde -> It is in front of the bank.",
    "Bankanın arkasında -> It is behind the bank.",
    "Bankanın yanında -> It is next to the bank.",
    "Bankanın yakınında -> It is near/close to the bank.",
    "Bankanın karşısında -> It is opposite the bank.",
    "Banka ile postanenin arasında -> It is between the bank and the post office.",
    "Masanın üzerinde. -> It is on the table.",
    "Masanın altında. -> It is under the table.",
    "Kutunun içinde. -> It is in the box.",
    "Arabam(benim) nerede? -> Where is my car?",
    "Araban(senin) nerede? -> Where is your car?",
    "Arabamız(Bizim) nerede? -> Where is our car?",
    "Arabası(Onun) nerede?(Erkek) -> Where is his car?",
    "Arabası(Onun) nerede?(Kadın) -> Where is her car?",
    "Arabaları(Onların) nerede? -> Where is their car?",
    "Saat kaç? -> What time is it?",
    "Saat 4. -> It is four o'clock.",
    "Saat 4'ü 10 geçiyor. -> It is ten past four o'clock.",
    "Saat 4'ü çeyrek geçiyor. -> It is quarter past four o'clock.",
    "Saat 4.5 -> It is half past four o'clock.",
    "Saat 5'e 10 var. -> It is ten to five o'clock.",
    "Saat 5'e 15 var. -> It is quarter to five o'clock.",
    "Bugün hava nasıl? -> How is the weather today?",
    "Hava bugün güneşli. -> It is sunny today.",
    "Hava bugün bulutlu. -> It is cloudy today.",
    "Hava bugün yağmurlu. -> It is rainy today.",
    "Hava bugün karlı. -> It is snowy today.",
    "Hava bugün sisli. -> It is foggy today.",
    "Hava bugün rüzgarlı. -> It is windy today.",
    "Hava bugün fırtınalı. -> It is stormy today."
];

// Function to create a random translation card
function createRandomTranslationCard() {
    const container = document.getElementById('translation-cards');
    container.innerHTML = '';

    // Choose a random translation
    const randomIndex = Math.floor(Math.random() * translations.length);
    const [turkish, english] = translations[randomIndex].split(' -> ');
    console.log(turkish, '->', english);

    const card = document.createElement('div');
    card.classList.add('card', 'bg-white', 'shadow-lg', 'rounded-lg', 'overflow-hidden', 'cursor-pointer', 'flex', 'justify-center', 'items-center');
    card.style.width = '400px';
    card.style.height = '250px';

    const inner = document.createElement('div');
    inner.classList.add('card-inner');
    inner.style.transition = 'transform 0.8s';
    inner.style.transformStyle = 'preserve-3d';

    const front = document.createElement('div');
    front.classList.add('front', 'text-center', 'text-gray-800');
    front.textContent = turkish;

    const back = document.createElement('div');
    back.classList.add('back', 'text-center', 'text-gray-800');
    back.textContent = english;

    inner.appendChild(front);
    inner.appendChild(back);
    card.appendChild(inner);
    container.appendChild(card);

    // Add click event to flip the card and update the English value
    let isFlipped = false;
    card.addEventListener('click', () => {
        if (!isFlipped) {
            inner.style.transform = 'rotateY(180deg)';
            isFlipped = true;
        } else {
            // Rotate the card back to the front side
            inner.style.transform = 'rotateY(0deg)';
            isFlipped = false;

            var red = Math.floor(Math.random() * 256);
            var green = Math.floor(Math.random() * 256);
            var blue = Math.floor(Math.random() * 256);
            // RGB değerlerini birleştirerek CSS uyumlu bir renk oluştur
            var randomColor = "rgb(" + red + "," + green + "," + blue + ")";
            container.style.backgroundColor = randomColor

            // Choose a new random translation after 0.1 second
            setTimeout(() => {
                const newIndex = Math.floor(Math.random() * translations.length);
                console.log()
                const [newTurkish, newEnglish] = translations[newIndex].split(' -> ');

                // Update the English value on the card
                front.textContent = newTurkish
                back.textContent = newEnglish;
                console.log(newIndex + "/" + translations.length + ": " + newTurkish, '->', newEnglish);
            }, 100);
        }
    });
}

// Add click event to update the English value



// Create a random translation card when the page loads
document.addEventListener('DOMContentLoaded', () => {
    createRandomTranslationCard();
});
